add qbittorrent readiness probe for IP

diff --git a/apps/qbittorrent-vpn/deployment.yaml b/apps/qbittorrent-vpn/deployment.yaml
--- a/apps/qbittorrent-vpn/deployment.yaml
+++ b/apps/qbittorrent-vpn/deployment.yaml
@@ -77,6 +77,26 @@ spec:
               mountPath: /config
             - name: qbittorrent-torrents
               mountPath: /data/torrents
+          readinessProbe:
+            exec:
+              command:
+                - /bin/sh
+                - -c
+                - |
+                  # Fetch geolocation information
+                  geo_info=$(curl -s http://ipinfo.io/json)
+                  
+                  # Extract the region (state) from the response using grep
+                  state=$(echo $geo_info | grep -oP '"region":\s*"\K[^"]+')
+                  
+                  # Check if the state is Florida
+                  if [ "$state" == "Florida" ]; then
+                    exit 1  # Fail if the state is Florida
+                  fi
+            initialDelaySeconds: 10
+            periodSeconds: 300
+            failureThreshold: 3
+            successThreshold: 1
 
 ---
 apiVersion: v1
